[package]
name = "logiclong"
version = "0.1.0"
edition = "2021"
authors = ["amaanq"]
description = "Supercell's Logic Long implemented in Rust"
license = "MIT"

[dependencies]
rand = "0.8.5"
regex = "1"